name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-test-analyze:
    runs-on: macos-14
    timeout-minutes: 10
    steps:
      - name: Check out source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Build and test
        run: |
          make test
          make
      - name: Static analysis
        run: make analyze
